{% set name = "pycryptodome" %}
{% set version = "3.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ae0dd1bcfada451c35f9e29a3e5db385caabc190f98e4a80ad02a61098fb776

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - gmp   # [not win]
  run:
    - python
    - gmp   # [not win]

test:
  imports:
    - Crypto
    - Crypto.Cipher
    - Crypto.Hash
    - Crypto.IO
    - Crypto.Math
    - Crypto.Protocol
    - Crypto.PublicKey
    - Crypto.Random
    - Crypto.SelfTest
    - Crypto.SelfTest.Cipher
    - Crypto.SelfTest.Hash
    - Crypto.SelfTest.IO
    - Crypto.SelfTest.Math
    - Crypto.SelfTest.Protocol
    - Crypto.SelfTest.PublicKey
    - Crypto.SelfTest.Random
    - Crypto.SelfTest.Signature
    - Crypto.SelfTest.Util
    - Crypto.Signature
    - Crypto.Util

about:
  home: http://www.pycryptodome.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Cryptographic library for Python
  doc_url: https://www.pycryptodome.org/en/latest/
  dev_url: https://github.com/Legrandin/pycryptodome

extra:
  recipe-maintainers:
    - mariusvniekerk
    - benhuff
    - nehaljwani
