appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: VpxOnqRAzsacRLjFTkfdZj/yWN/G+uDYD87etKb7ZfX9wzXTc9EF7oUmzcYPOUCubNDJ19uaTONsGfWYajZPKfEXtZijjHtHU9GkLhui/RRf2piSsa2nl7nXxZW1vj5zrG5REW9QpUFbOqH6oeqYihchpUEmTvD93RokQVWjINLL3QZUdNXVHrxIh9NCMk/V2YAQ2dOIbnk4vPLg3E+jbq+U7zn7nUErZj0seAnQjsrxra3XRJ4Q8oXAgYzvV06rMUVSfKxDGFmpmSSMr9I5CtvdGboXYfEGBjq0vSQ+AqQMoUVRIBd3v/MTIh+z5SCAPWcDCTpPg0NXkforjb0FMo1xx0HcmNKztxDwkmnW5W1qfuJEuQgyp0a0HPn92Gf9Ji0BqCaiHUD8E+XK8s/HiquNd9y1IVYI91xPXnO6Q4k06OSqqOM8TIKAXonmOVDq/3FGfrZMf4O61uRQSepB6l1yh9TSzRmZGnVN0MbkOSO0/t+m5zL5IjU5y5rmOaRbhOoXXPxYb9fSJDF2ksPy4EE6Zu2UGm7IuIA2d+rYgZtIxhFevia9+leLhxUglbEHRUD1mOQr+ypa7YJ7PUsrtl1sfRrTwdQUn9IcHwt8KGIx0IgLnjf/bPxwsXkSkd98uNKbAXW3BmtT0MQvhKWg3DGZdzrLBC5sMRVrnqINR34=}
provider:
  win: azure
conda_forge_output_validation: true
